defmodule Curriclick.Companies.JobApplication.DraftAnswer do
  @moduledoc """
  Represents a draft answer generated by the AI.
  """
  use Ash.Resource,
    data_layer: :embedded

  attributes do
    attribute :requirement_id, :uuid do
      public? true
      allow_nil? false
    end

    attribute :answer, :string do
      public? true
      allow_nil? false
    end

    attribute :confidence_score, :atom do
      constraints [one_of: [:low, :medium, :high]]
      public? true
      allow_nil? false
    end

    attribute :confidence_explanation, :string do
      public? true
    end

    attribute :missing_info, :string do
      public? true
    end
  end
end
