// Generated by AshTypescript
// Do not edit this file manually





export type UUID = string;

// JobListing Schema
export type JobListingResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "jobRoleName" | "description" | "companyId";
  id: UUID;
  jobRoleName: string;
  description: string;
  companyId: UUID;
  company: { __type: "Relationship"; __resource: CompanyResourceSchema | null; };
  matchScore: { __type: "ComplexCalculation"; __returnType: number | null; __args: { searchVector?: Array<number> }; };
  cosineDistance: { __type: "ComplexCalculation"; __returnType: number | null; __args: { vector1?: Array<number>; vector2?: Array<number> }; };
};



// Company Schema
export type CompanyResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description";
  id: UUID;
  name: string;
  description: string | null;
};









export type JobListingFilterInput = {
  and?: Array<JobListingFilterInput>;
  or?: Array<JobListingFilterInput>;
  not?: Array<JobListingFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  jobRoleName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  companyId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  matchScore?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  cosineDistance?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };


  company?: CompanyFilterInput;

};
export type CompanyFilterInput = {
  and?: Array<CompanyFilterInput>;
  or?: Array<CompanyFilterInput>;
  not?: Array<CompanyFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};


// Utility Types

// Resource schema constraint
type TypedSchema = {
  __type: "Resource" | "TypedStruct" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? UnionSchema[UnionKey] extends { __type: "TypedMap"; __primitiveFields: any }
                ? UnionSchema[UnionKey]
                : UnionSchema[UnionKey] extends TypedSchema
                  ? InferResult<UnionSchema[UnionKey], FieldSelection[FieldIndex][UnionKey]>
                  : never
              : never;
          }
        : never;
  }[number]
>;

type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
        ? T[K] extends { __array: true }
          ? (PrimitiveFields | {
              [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: T[K][UnionKey] extends { __type: "TypedMap"; __primitiveFields: any }
                ? T[K][UnionKey]["__primitiveFields"][]
                : T[K][UnionKey] extends TypedSchema
                  ? UnifiedFieldSelection<T[K][UnionKey]>[]
                  : never;
            })[]
          : (PrimitiveFields | {
              [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: T[K][UnionKey] extends { __type: "TypedMap"; __primitiveFields: any }
                ? T[K][UnionKey]["__primitiveFields"][]
                : T[K][UnionKey] extends TypedSchema
                  ? UnifiedFieldSelection<T[K][UnionKey]>[]
                  : never;
            })[]
          : NonNullable<T[K]> extends TypedSchema
            ? UnifiedFieldSelection<NonNullable<T[K]>>[]
            : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : T[K] extends { __type: "Union"; __primitiveFields: any }
              ? T[K] extends { __array: true }
                ? {
                    [CurrentK in K]: T[CurrentK] extends { __type: "Union"; __primitiveFields: any }
                      ? Field[CurrentK] extends any[]
                        ? Array<InferUnionFieldValue<T[CurrentK], Field[CurrentK]>> | null
                        : never
                      : never
                  }
                : {
                    [CurrentK in K]: T[CurrentK] extends { __type: "Union"; __primitiveFields: any }
                      ? Field[CurrentK] extends any[]
                        ? InferUnionFieldValue<T[CurrentK], Field[CurrentK]> | null
                        : never
                      : never
                  }
                : NonNullable<T[K]> extends TypedSchema
                  ? null extends T[K]
                    ? InferResult<NonNullable<T[K]>, Field[K]> | null
                    : InferResult<NonNullable<T[K]>, Field[K]>
                  : never
          : never;
      }
    : never;

type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call
 * @example
 * const error: AshRpcError = { type: "validation_error", message: "Something went wrong" }
 */
export type AshRpcError = {
  type: string;
  message: string;
  field?: string;
  fieldPath?: string;
  details?: Record<string, any>;
}





// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  primaryKey?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: Record<string, any>; // Metadata field selection

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...config.headers,
    ...processedConfig.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...config.fetchOptions,
    ...processedConfig.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network",
          message: response.statusText,
          details: {}
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...config.headers,
    ...processedConfig.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...config.fetchOptions,
    ...processedConfig.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network",
          message: response.statusText,
          details: {}
        }
      ],
    } as T;
  }

  return result as T;
}









export type ListJobListingsFields = UnifiedFieldSelection<JobListingResourceSchema>[];
type InferListJobListingsResult<
  Fields extends ListJobListingsFields,
> = Array<InferResult<JobListingResourceSchema, Fields>>;

export type ListJobListingsResult<Fields extends ListJobListingsFields> = | { success: true; data: InferListJobListingsResult<Fields>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function listJobListings<Fields extends ListJobListingsFields>(
  config: {
  fields: Fields;
  filter?: JobListingFilterInput;
  sort?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListJobListingsResult<Fields>> {
  const payload = {
    action: "list_job_listings",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort })
  };

  return executeActionRpcRequest<ListJobListingsResult<Fields>>(
    payload,
    config
  );
}


export type ValidateListJobListingsResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateListJobListings(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateListJobListingsResult> {
  const payload = {
    action: "list_job_listings"
  };

  return executeValidationRpcRequest<ValidateListJobListingsResult>(
    payload,
    config
  );
}


export type GetJobListingFields = UnifiedFieldSelection<JobListingResourceSchema>[];
type InferGetJobListingResult<
  Fields extends GetJobListingFields,
> = Array<InferResult<JobListingResourceSchema, Fields>>;

export type GetJobListingResult<Fields extends GetJobListingFields> = | { success: true; data: InferGetJobListingResult<Fields>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function getJobListing<Fields extends GetJobListingFields>(
  config: {
  fields: Fields;
  filter?: JobListingFilterInput;
  sort?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetJobListingResult<Fields>> {
  const payload = {
    action: "get_job_listing",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort })
  };

  return executeActionRpcRequest<GetJobListingResult<Fields>>(
    payload,
    config
  );
}


export type ValidateGetJobListingResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateGetJobListing(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateGetJobListingResult> {
  const payload = {
    action: "get_job_listing"
  };

  return executeValidationRpcRequest<ValidateGetJobListingResult>(
    payload,
    config
  );
}


export type FindMatchingJobsInput = {
  idealJobDescription: string;
  limit?: number;
};

export type FindMatchingJobsValidationErrors = {
  idealJobDescription?: string[];
  limit?: string[];
};

export type FindMatchingJobsFields = UnifiedFieldSelection<JobListingResourceSchema>[];
type InferFindMatchingJobsResult<
  Fields extends FindMatchingJobsFields,
> = Array<InferResult<JobListingResourceSchema, Fields>>;

export type FindMatchingJobsResult<Fields extends FindMatchingJobsFields> = | { success: true; data: InferFindMatchingJobsResult<Fields>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function findMatchingJobs<Fields extends FindMatchingJobsFields>(
  config: {
  input: FindMatchingJobsInput;
  fields: Fields;
  filter?: JobListingFilterInput;
  sort?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<FindMatchingJobsResult<Fields>> {
  const payload = {
    action: "find_matching_jobs",
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort })
  };

  return executeActionRpcRequest<FindMatchingJobsResult<Fields>>(
    payload,
    config
  );
}


export type ValidateFindMatchingJobsResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateFindMatchingJobs(
  config: {
  input: FindMatchingJobsInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateFindMatchingJobsResult> {
  const payload = {
    action: "find_matching_jobs",
    input: config.input
  };

  return executeValidationRpcRequest<ValidateFindMatchingJobsResult>(
    payload,
    config
  );
}


export type ListCompaniesFields = UnifiedFieldSelection<CompanyResourceSchema>[];


type InferListCompaniesResult<
  Fields extends ListCompaniesFields | undefined,
  Page extends ListCompaniesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<CompanyResourceSchema, Fields>>, {
  results: Array<InferResult<CompanyResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<CompanyResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListCompaniesConfig = {
  fields: ListCompaniesFields;
  filter?: CompanyFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListCompaniesResult<Fields extends ListCompaniesFields, Page extends ListCompaniesConfig["page"] = undefined> = | { success: true; data: InferListCompaniesResult<Fields, Page>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function listCompanies<Fields extends ListCompaniesFields, Config extends ListCompaniesConfig = ListCompaniesConfig>(
  config: Config & { fields: Fields }
): Promise<ListCompaniesResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_companies",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListCompaniesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type ValidateListCompaniesResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateListCompanies(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateListCompaniesResult> {
  const payload = {
    action: "list_companies"
  };

  return executeValidationRpcRequest<ValidateListCompaniesResult>(
    payload,
    config
  );
}


