defmodule Curriclick.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_applications) do
      remove :keywords
      add :keywords, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:job_applications) do
      remove :keywords
      add :keywords, {:array, :text}, default: []
    end
  end
end
