defmodule Curriclick.Repo.Migrations.RemoveUserIdealJobDescription do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :ideal_job_vector
      remove :ideal_job_description
    end
  end

  def down do
    alter table(:users) do
      add :ideal_job_description, :text
      add :ideal_job_vector, :vector, size: 1536
    end
  end
end
