defmodule Curriclick.Repo.Migrations.AddConversationToJobApplication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_applications) do
      remove :match_score

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "job_applications_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :summary, :text
      add :pros, {:array, :text}, default: []
      add :cons, {:array, :text}, default: []
      add :keywords, {:array, :text}, default: []
      add :match_quality, :text
      add :missing_info, :text
    end
  end

  def down do
    drop constraint(:job_applications, "job_applications_conversation_id_fkey")

    alter table(:job_applications) do
      remove :missing_info
      remove :match_quality
      remove :keywords
      remove :cons
      remove :pros
      remove :summary
      remove :conversation_id
      add :match_score, :float
    end
  end
end
