defmodule Curriclick.Repo.Migrations.AddDetailsToApplication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_applications) do
      add :search_query, :text
      add :match_score, :float
    end
  end

  def down do
    alter table(:job_applications) do
      remove :match_score
      remove :search_query
    end
  end
end
