defmodule Curriclick.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    ALTER TABLE users
    ADD COLUMN IF NOT EXISTS profile_job_interests text,
    ADD COLUMN IF NOT EXISTS profile_education text,
    ADD COLUMN IF NOT EXISTS profile_skills text,
    ADD COLUMN IF NOT EXISTS profile_experience text,
    ADD COLUMN IF NOT EXISTS profile_remote_preference text,
    ADD COLUMN IF NOT EXISTS profile_custom_instructions text
    """)
  end

  def down do
    alter table(:users) do
      remove :profile_custom_instructions, if_exists: true
      remove :profile_remote_preference, if_exists: true
      remove :profile_experience, if_exists: true
      remove :profile_skills, if_exists: true
      remove :profile_education, if_exists: true
      remove :profile_job_interests, if_exists: true
    end
  end
end
