defmodule Curriclick.Repo.Migrations.RevertContextAttribute do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      remove :context
    end
  end

  def down do
    alter table(:conversations) do
      add :context, :text, null: false, default: "job_search"
    end
  end
end
