defmodule Curriclick.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_listings) do
      add :ideal_job_description, :text
    end
  end

  def down do
    alter table(:job_listings) do
      remove :ideal_job_description
    end
  end
end
