defmodule Curriclick.Repo.Migrations.AddConfidenceToAnswers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_application_answers) do
      add :confidence_score, :text
      add :confidence_explanation, :text
      add :missing_info, :text
    end
  end

  def down do
    alter table(:job_application_answers) do
      remove :missing_info
      remove :confidence_explanation
      remove :confidence_score
    end
  end
end
