defmodule Curriclick.Repo.Migrations.AddJobRequirementsResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:job_listing_requirements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :question, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :job_listing_id,
          references(:job_listings,
            column: :id,
            name: "job_listing_requirements_job_listing_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:job_application_answers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :answer, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :job_application_id,
          references(:job_applications,
            column: :id,
            name: "job_application_answers_job_application_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :requirement_id,
          references(:job_listing_requirements,
            column: :id,
            name: "job_application_answers_requirement_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:job_application_answers, "job_application_answers_job_application_id_fkey")

    drop constraint(:job_application_answers, "job_application_answers_requirement_id_fkey")

    drop table(:job_application_answers)

    drop constraint(:job_listing_requirements, "job_listing_requirements_job_listing_id_fkey")

    drop table(:job_listing_requirements)
  end
end
