defmodule Curriclick.Repo.Migrations.UpdateJobListingColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:job_listings), :job_role_name, to: :title

    alter table(:job_listings) do
      remove :employment_type
      remove :location_type
      modify :pay_period, :text, default: nil
      add :remote_allowed, :boolean
      add :work_type, :text
      add :formatted_work_type, :text
      add :med_salary, :decimal
      add :views, :bigint
      add :applies, :bigint
      add :original_listed_time, :float
      add :listed_time, :float
      add :expiry, :float
      add :closed_time, :float
      add :job_posting_url, :text
      add :application_url, :text
      add :application_type, :text
      add :formatted_experience_level, :text
      add :skills_desc, :text
      add :posting_domain, :text
      add :sponsored, :bigint
      add :compensation_type, :text
      add :normalized_salary, :decimal
      add :zip_code, :text
      add :fips, :text
    end
  end

  def down do
    rename table(:job_listings), :title, to: :job_role_name

    alter table(:job_listings) do
      remove :fips
      remove :zip_code
      remove :normalized_salary
      remove :compensation_type
      remove :sponsored
      remove :posting_domain
      remove :skills_desc
      remove :formatted_experience_level
      remove :application_type
      remove :application_url
      remove :job_posting_url
      remove :closed_time
      remove :expiry
      remove :listed_time
      remove :original_listed_time
      remove :applies
      remove :views
      remove :med_salary
      remove :formatted_work_type
      remove :work_type
      remove :remote_allowed
      modify :pay_period, :text, default: "monthly"
      add :location_type, :text
      add :employment_type, :text
    end
  end
end
