defmodule Curriclick.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_applications) do
      add :match_quality_explanation, :text
      add :hiring_probability_explanation, :text
    end
  end

  def down do
    alter table(:job_applications) do
      remove :hiring_probability_explanation
      remove :match_quality_explanation
    end
  end
end
