defmodule Curriclick.Repo.Migrations.AddJobCardsToConversation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :profile_job_interests, :text
      add :profile_education, :text
      add :profile_skills, :text
      add :profile_experience, :text
      add :profile_remote_preference, :text
      add :profile_custom_instructions, :text
      add :profile_first_name, :text
      add :profile_last_name, :text
      add :profile_birth_date, :date
      add :profile_location, :text
      add :profile_cpf, :text
      add :profile_phone, :text
    end

    alter table(:conversations) do
      add :job_cards, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:conversations) do
      remove :job_cards
    end

    alter table(:users) do
      remove :profile_phone
      remove :profile_cpf
      remove :profile_location
      remove :profile_birth_date
      remove :profile_last_name
      remove :profile_first_name
      remove :profile_custom_instructions
      remove :profile_remote_preference
      remove :profile_experience
      remove :profile_skills
      remove :profile_education
      remove :profile_job_interests
    end
  end
end
