defmodule Curriclick.Repo.Migrations.AddMatchScoresToJobApplication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_applications) do
      add :work_type_score, :map
      add :location_score, :map
      add :salary_score, :map
      add :remote_score, :map
      add :skills_score, :map
    end
  end

  def down do
    alter table(:job_applications) do
      remove :skills_score
      remove :remote_score
      remove :salary_score
      remove :location_score
      remove :work_type_score
    end
  end
end
