defmodule Curriclick.Repo.Migrations.CorrectJobListingFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:job_listings), :work_type, to: :location_type

    alter table(:job_listings) do
      add :employment_type, :text
    end
  end

  def down do
    alter table(:job_listings) do
      remove :employment_type
    end

    rename table(:job_listings), :location_type, to: :work_type
  end
end
