defmodule Curriclick.Repo.Migrations.AddOriginalId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_listings) do
      add :original_id, :text
    end
  end

  def down do
    alter table(:job_listings) do
      remove :original_id
    end
  end
end
