defmodule Curriclick.Repo.Migrations.AddJobApplication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:job_applications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "job_applications_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :job_listing_id,
          references(:job_listings,
            column: :id,
            name: "job_applications_job_listing_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:job_applications, [:user_id, :job_listing_id],
             name: "job_applications_unique_application_index"
           )
  end

  def down do
    drop_if_exists unique_index(:job_applications, [:user_id, :job_listing_id],
                     name: "job_applications_unique_application_index"
                   )

    drop constraint(:job_applications, "job_applications_user_id_fkey")

    drop constraint(:job_applications, "job_applications_job_listing_id_fkey")

    drop table(:job_applications)
  end
end
