defmodule Curriclick.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_applications) do
      add :hiring_probability, :float
    end
  end

  def down do
    alter table(:job_applications) do
      remove :hiring_probability
    end
  end
end
