defmodule Curriclick.Repo.Migrations.AddUniqueReqIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:job_listing_requirements, [:job_listing_id, :question],
             name: "job_listing_requirements_unique_req_index"
           )
  end

  def down do
    drop_if_exists unique_index(:job_listing_requirements, [:job_listing_id, :question],
                     name: "job_listing_requirements_unique_req_index"
                   )
  end
end
