defmodule Curriclick.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add_if_not_exists :profile_first_name, :text
      add_if_not_exists :profile_last_name, :text
      add_if_not_exists :profile_birth_date, :date
      add_if_not_exists :profile_location, :text
      add_if_not_exists :profile_cpf, :text
      add_if_not_exists :profile_phone, :text
    end
  end

  def down do
    alter table(:users) do
      remove_if_exists :profile_phone, :text
      remove_if_exists :profile_cpf, :text
      remove_if_exists :profile_location, :text
      remove_if_exists :profile_birth_date, :date
      remove_if_exists :profile_last_name, :text
      remove_if_exists :profile_first_name, :text
    end
  end
end
