defmodule Curriclick.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:job_listings) do
      remove :test_echo_message
    end
  end

  def down do
    alter table(:job_listings) do
      add :test_echo_message, :text
    end
  end
end
